# Generated by Django 6.0.3 on 2026-03-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=25, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('autores', models.CharField(max_length=200, verbose_name='Autores')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais')),
                ('editora', models.CharField(blank=True, max_length=50, null=True, verbose_name='Editora')),
                ('edicao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edicao')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('emprestado', 'Emprestado')], default='disponivel', max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'livro',
                'ordering': ['titulo'],
            },
        ),
    ]
