# Generated by Django 6.0.3 on 2026-03-13 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leitor', '0001_initial'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data do emprestimo')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data da devolucao')),
                ('data_limite', models.DateTimeField(verbose_name='Data limite')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado'), ('renovado', 'Renovado')], default='ativo', max_length=15, verbose_name='Status')),
                ('renovacoes', models.IntegerField(default=0, verbose_name='Numero de renovacoes')),
                ('id_leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='leitor.leitor', verbose_name='Leitor')),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='livro.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'db_table': 'emprestimo',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
