# Generated by Django 6.0.3 on 2026-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
